Add authentication token receiving from the querystring
multinet-app/view-adjmatrix pull request #104
Opened 2020-09-16 20:38 UTC by JackWilb

2020-09-17 14:25 UTC, AlmightyYakob requested changes
Small things, otherwise good

2020-09-17 14:25 UTC, AlmightyYakob commented on src/components/Controls.vue
> +const loginTokenRegex = /&token=(\S+)/;
See https://github.com/multinet-app/multinet-client/pull/124#discussion_r490283373

2020-09-17 14:25 UTC, AlmightyYakob commented on src/components/Controls.vue
> +      return '';
I think it'd be better if the token was explicitly null when missing, only calling `setAuthToken` when it's not null, as there's really no point in setting the token to `''`.

2020-09-17 14:25 UTC, AlmightyYakob commented on src/lib/multinet.ts
> +  api.setAuthToken(token);
Related to my comment above regarding null token value, there would be a check here against that.

2020-09-18 15:16 UTC, waxlamp requested changes

2020-09-18 15:16 UTC, waxlamp commented on src/components/Controls.vue
> +      const result = loginTokenRegex.exec(window.location.href);
Why is the regex declared globally? The code would be more readable if it was just used here directly.

2020-09-18 15:16 UTC, waxlamp commented on src/components/Controls.vue
> +        const newPath = window.location.href.slice(0, index);
This is pretty brittle. If the login token argument isn't the last thing in the URL, you're going to throw away some parts of it by accident.

Maybe a better approach is the fragment-based one @AlmightyYakob used for the client. @AlmightyYakob, thoughts?

2020-09-18 15:43 UTC, AlmightyYakob commented on src/components/Controls.vue
> +      const result = loginTokenRegex.exec(window.location.href);
I don't see a reason not to declare it globally, otherwise the variable would need to be recreated here unnecessarily every time it's called.

2020-09-18 15:44 UTC, AlmightyYakob commented on src/components/Controls.vue
> +      const result = loginTokenRegex.exec(window.location.href);
I guess moreover, that regex isn't dependent on anything in this function, and is completely constant.

2020-09-18 16:36 UTC, AlmightyYakob commented on src/components/Controls.vue
> +        const newPath = window.location.href.slice(0, index);
This is the same implementation as what I've done in the client. I think it's reasonable to assume that the token will be the last fragment in the URL. However it wouldn't be too hard to remove just the matching section of the URL, leaving what's before and after.

2020-09-18 17:06 UTC, AlmightyYakob commented on src/components/Controls.vue
> +        const newPath = window.location.href.slice(0, index);
No you're correct, I didn't notice that. @JackWilb I would also say it should be in the fragment

2020-09-21 16:10 UTC, JackWilb commented on src/components/Controls.vue
> +      const result = loginTokenRegex.exec(window.location.href);
I was following the style from the client here. I can update if necessary

2020-09-21 16:13 UTC, JackWilb commented on src/components/Controls.vue
> +const loginTokenRegex = /&token=(\S+)/;
See 2291479

2020-09-21 16:13 UTC, JackWilb commented on src/components/Controls.vue
> +      return '';
See 2291479

2020-09-21 16:13 UTC, JackWilb commented on src/lib/multinet.ts
> +  api.setAuthToken(token);
See 2291479

2020-09-21 16:33 UTC, JackWilb commented on src/components/Controls.vue
> +        const newPath = window.location.href.slice(0, index);
See e2c732a

2020-09-21 16:35 UTC, AlmightyYakob commented on src/components/Controls.vue
> +      const result = loginTokenRegex.exec(window.location.href);
@waxlamp okay with leaving the regex declared globally?

2020-09-21 16:44 UTC, waxlamp commented on src/components/Controls.vue
> +      const result = loginTokenRegex.exec(window.location.href);
It's ok to leave it for now, but this is a classic case of "globals are bad". For example, if you move this function to somewhere else, but you forget the regex, it will break. Anyone reading this function for the first time will wonder where the variable came from, and have to find it at the top of the file, etc. And the argument about recreating it needlessly on every invocation is an example of premature optimization--we don't call this function very often, and it's really the compiler's job to recognize that this value never changes and do that sort of constant-factoring for us, etc.

I'm ok with leaving this as-is mainly because we're planning to refactor this out into multinetjs sometime soon. But in general, I don't like having a core part of this function defined as a global.

2020-09-21 16:56 UTC, waxlamp approved these changes

2020-09-21 18:07 UTC, AlmightyYakob commented on src/components/Controls.vue
> +      const result = loginTokenRegex.exec(window.location.href);
Good point about portability, I hadn't thought about that. I agree that I don't think it matters for now.

2020-09-25 17:05 UTC, AlmightyYakob approved these changes

2020-09-25 17:22 UTC, merged