Implement the legend for the matrix in the matrix controls panel
multinet-app/view-adjmatrix pull request #105
Opened 2020-09-22 16:16 UTC by mozartfish

2020-09-22 18:20 UTC, JackWilb requested changes
Please remove the whole yarn-error.log file, it's making it look like there are huge changes here.

Also, I think we should extract this logic into its own function in `methods:` and then call it from `mounted()` to keep it a bit more organized

2020-09-22 18:20 UTC, JackWilb commented on src/components/Controls.vue
> +    const minNumConnections = min(neighborsList);
We should use the computed max number of connections per cell here

2020-09-22 18:20 UTC, JackWilb commented on yarn-error.log
> +  /usr/bin/node /usr/share/yarn/bin/yarn.js add @types/d3-legend
Remove this whole file

2020-09-22 18:20 UTC, JackWilb commented on src/components/Controls.vue
> +              <svg id="matrix-legend"></svg>
```suggestion
              Matrix Legend
              <svg id="matrix-legend"></svg>
```

2020-09-22 18:20 UTC, JackWilb commented on src/components/Controls.vue
>    },
```suggestion
    legendSVG.select('.legendLinear').call(legendLinear);
  },
```

2020-09-22 18:20 UTC, JackWilb commented on src/components/Controls.vue
> +    const minNumConnections = min(neighborsList);
You should consider spacing out your comments more

2020-09-25 18:39 UTC, JackWilb requested changes
This looks great Pranav, and could honestly be merged in as is. However, I think you could simplify the logic a bit if instead of emitting the `maxNumConnections`, you just emit the scale and then use that for building the legend

2020-09-25 18:39 UTC, JackWilb commented on src/components/Controls.vue
> +      // set up color scale (currently only supports continuous data)
```suggestion
    createLegend(maxConnections: number) {
      // set up color scale (currently only supports continuous data)
```

2020-09-25 18:39 UTC, JackWilb commented on src/components/Controls.vue
> +        .range(['#feebe2', '#690000']);
Just a thought. Instead of passing up the maxNumConnections like you have now. How about if we just pass the scale up. Then we wouldn't need to define a new scale here and the colors would update if we changed them in the methods.ts file

2020-09-25 18:39 UTC, JackWilb commented on src/components/Controls.vue
>              }"
```suggestion
              visualizedAttributes,
            }"
```

2020-09-25 19:22 UTC, JackWilb requested changes
Ping me when you're done with these changes and let's see if we can fix these typescript errors on the build

2020-09-25 19:22 UTC, JackWilb commented on src/components/AdjMatrix/AdjMatrix.vue
> +    this.$emit('updateMaxNumConnections', this.view.colorScale);
Change the event name, `updateMaxNumConnections` isn't what we're doing anymore. We're passing the whole scale

2020-09-25 19:22 UTC, JackWilb commented on src/components/AdjMatrix/AdjMatrixMethods.ts
This is already imported on line 2
```suggestion
import { Link, Network, Node, Cell, State } from '@/types';

```

2020-09-25 19:22 UTC, JackWilb commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +    //   .range(['#feebe2', '#690000']); // TODO: colors here are arbitrary, change later
```suggestion
```

2020-09-25 19:22 UTC, JackWilb commented on src/components/Controls.vue
> +            @updateMaxNumConnections="createLegend"
When you update the name of the event in the emit, it will need to be changed here, too.

2020-09-25 19:22 UTC, JackWilb commented on src/components/Controls.vue
> +import { ScaleLinear,} from 'd3-scale';
```suggestion
import { ScaleLinear } from 'd3-scale';
```

2020-09-25 19:22 UTC, JackWilb commented on src/components/Controls.vue
> +      const legendSVG = select('#matrix-legend');
```suggestion
    createLegend(colorScale: ScaleLinear<string, number>) {
      const legendSVG = select('#matrix-legend');
```

2020-09-25 21:58 UTC, waxlamp requested changes
This looks good at a glance. One thing to fix is that you seem to have checked in a yarn error file; please make sure that's removed from source control.

The only other comment I have is that the color legend should *probably* be its own Vue component. But that's something we can address later.

2020-09-25 22:17 UTC, JackWilb commented
> This looks good at a glance. One thing to fix is that you seem to have checked in a yarn error file; please make sure that's removed from source control.

@mozartfish You should make a commit that removes the file and adds it to the .gitignore so it doesn't keep getting accidentally added.

2020-09-25 22:24 UTC, waxlamp commented
> > This looks good at a glance. One thing to fix is that you seem to have checked in a yarn error file; please make sure that's removed from source control.
> 
> @mozartfish You should make a commit that removes the file and adds it to the .gitignore so it doesn't keep getting accidentally added.

The other thing is: don't use commands like `git add *` (not sure if this is what happened); instead, be very explicit about adding files.

2020-09-28 14:54 UTC, waxlamp approved these changes
There is a blank line at the end of a file that you should strike, but otherwise this looks good. Thanks!

2020-09-28 14:54 UTC, waxlamp commented on .gitignore
> +
```suggestion
```

2020-09-28 16:15 UTC, JackWilb approved these changes

2020-09-28 16:28 UTC, merged