Sidebar ui update
multinet-app/view-adjmatrix pull request #82
Opened 2020-08-12 18:50 UTC by jtomeck

This PR creates the groundwork for the updated sidebar UI. Nothing is hooked up or functional, this was just to get the components placed and to further discuss the functionality needed.

2020-09-02 21:50 UTC, waxlamp requested changes
Thanks for everyone's efforts on this branch.

I just had one suggestion to tighten up a type, and I think one more direct code suggestion (to get rid of a comment that we don't need).

2020-09-02 21:50 UTC, waxlamp commented on src/components/Controls.vue
> +    connectivity: any,
Can we use a better type than `any`?

2020-09-02 21:50 UTC, waxlamp commented on src/components/Controls.vue
> +                  <!-- DERYA -->
```suggestion
```

2020-09-08 16:55 UTC, waxlamp commented on src/components/Controls.vue
> +                  <!-- DERYA -->
@gotdairyya, could you accept this code suggestion?

2020-09-08 16:56 UTC, waxlamp commented on src/components/Controls.vue
> +    connectivity: any,
@gotdairyya, let me know if you'd like me to address this? I can probably figure out what type to put in here.

2020-09-09 03:21 UTC, gotdairyya commented on src/components/Controls.vue
> +    connectivity: any,
@waxlamp Is any ok for now? Connectivity is a fill-in variable to hold the dropdown menu items, but if we refactor the sidebar as a form then I'm not sure we will need it

2020-09-09 16:15 UTC, waxlamp commented on src/components/Controls.vue
> +    connectivity: any,
Ah I see. I am surprised the linter doesn't complain about it. Yes this is ok for now. Could you add a comment above that line to explain what you just told me?

2020-09-14 13:58 UTC, waxlamp approved these changes

2020-09-14 14:48 UTC, waxlamp commented
I am working on resolving the conflicts in this PR--watch for a merge commit that does so.

2020-09-14 17:06 UTC, waxlamp commented
> I am working on resolving the conflicts in this PR--watch for a merge commit that does so.

This is done now, but I am not sure I resolved the conflicts properly. @jtomeck, if you could pull and build and verify this looks ok, we can merge.

2020-09-14 20:17 UTC, JackWilb approved these changes
Since this is going into the graffinity branch, it's okay that we're losing the settings toggles. We should be aware that we'll need a spot for them at some point though

2020-09-14 20:54 UTC, waxlamp commented
> Since this is going into the graffinity branch, it's okay that we're losing the settings toggles. We should be aware that we'll need a spot for them at some point though

Would you mind checking out an earlier revision from this PR branch and see if the controls are gone there too? If not, then I likely made a mistake in the merge commit.

2020-09-14 21:18 UTC, JackWilb commented
> > Since this is going into the graffinity branch, it's okay that we're losing the settings toggles. We should be aware that we'll need a spot for them at some point though
> 
> Would you mind checking out an earlier revision from this PR branch and see if the controls are gone there too? If not, then I likely made a mistake in the merge commit.

I remember them being removed in the earlier commits from Jared. We had talked about relocating them

2020-09-14 21:37 UTC, waxlamp commented
> > > Since this is going into the graffinity branch, it's okay that we're losing the settings toggles. We should be aware that we'll need a spot for them at some point though
> > 
> > 
> > Would you mind checking out an earlier revision from this PR branch and see if the controls are gone there too? If not, then I likely made a mistake in the merge commit.
> 
> I remember them being removed in the earlier commits from Jared. We had talked about relocating them

Thanks, Jack. @jtomeck, please give this a look as soon as you can, and if you're happy with it, please go ahead and merge it.

2020-09-16 16:03 UTC, merged