Labels foreign object prototype
multinet-app/view-adjmatrix pull request #93
Opened 2020-09-01 20:54 UTC by mozartfish

This prototype is a solution for how to handle the label cutoff problem with SVG text using SVG Foreign Objects.

This is a picture with the foreign objects for the rows 
![image](https://user-images.githubusercontent.com/24800816/91904945-9dfc7080-ec5a-11ea-95fc-095a5bf2378e.png)

currently working on foreign objects for columns

2020-09-01 21:33 UTC, mozartfish commented
Finished the row and column labels for the matrix.

Les Mis
![image](https://user-images.githubusercontent.com/24800816/91908166-013cd180-ec60-11ea-8381-8f1380b2d033.png)

Flight data 
![image](https://user-images.githubusercontent.com/24800816/91908231-14e83800-ec60-11ea-8e00-c15b8dfdb701.png)

2020-09-04 14:03 UTC, waxlamp requested changes
Looking good. I have several suggestions about how to improve the code, but the visuals are very nice.

Before merging:
- [ ] file an issue to hoist some of the DOM creation to the Vue layer

2020-09-04 14:03 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .attr('height', foreignObjectDimensionsConstant);
Since the width and height for these are set, and also used in the column labels below, I think you'd be better off making both of these `const` values that are more explicitly set. It also becomes easier to name these variables (`labelWidth` and `labelHeight`, or something like that).

2020-09-04 14:03 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .attr('x', -foreignObjectXConst + 95)
This `95` is a [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)) so maybe we can define the full expression as a constant, or at least give the `95` a name via a `const` variable.

2020-09-04 14:03 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .attr('height', foreignObjectDimensionsConstant);
See above comment; whatever solution is used there can be deployed in this instance as well.

2020-09-04 17:29 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .attr('z-index', 100)
The index is needed to show the importance of the labels when the highlight happens because if there is no z index, the highlight (which is an svg element) covers the label (a paragraph element within an svg element). To make sure the label has priority has over the highlight when a user hovers over a row/column, I used a index so the label can be seen while a user is highlighting a row/column

2020-09-04 17:30 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .attr('z-index', 100)
Just realized that I could put that in the css

2020-09-04 17:34 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .attr('z-index', 100)
put the z index in the vue file

2020-09-08 13:18 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .attr('z-index', 100)
Whether this stays here or moves to CSS, it will be important to leave a comment explaining what this is being used for. In general, hard-coding values like this (even when it's necessary) can lead to confusion later if there's no attending explanation.

2020-09-08 13:18 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .attr('z-index', 100)
> put the z index in the vue file

Do you mean you'll move this to the `<style>` section in the .vue file?

2020-09-08 15:21 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .attr('z-index', 100)
I moved this code to the css in the vue file

2020-09-09 16:31 UTC, JackWilb requested changes
Here are a couple issues I saw. We should clean these up and then rebase the commits at our meeting tomorrow and then it should be good to go

2020-09-09 16:31 UTC, JackWilb commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +    const labelContainerWidth = labelContainerHeight + 60;
Why is this 85 and not 75? You can remove this and just use `rowLabelContainerStart`. Since you're only moving the label 75 pixels left from the edge of the matrix, you shouldn't have the width of the element be 85.

2020-09-09 16:31 UTC, JackWilb commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .append('p')
You don't need to add a body each time, you can just add the p
```suggestion
      .attr('height', labelContainerHeight);

    const rowLabel = edgeRowForeignObject
      .append('xhtml:p')
```

2020-09-09 16:31 UTC, JackWilb commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .text((d: Node, i: number) => d._key)
```suggestion
      .text((d: Node) => d._key)
```

2020-09-09 16:31 UTC, JackWilb commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .text((d: Node, i: number) => d._key)
```suggestion
      .text((d: Node) => d._key)
```

2020-09-09 16:31 UTC, JackWilb commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .append('p')
```suggestion
      .attr('height', labelContainerHeight);

    const colLabel = edgeColumnForeignObject
      .append('xhtml:p')
```

2020-09-09 16:31 UTC, JackWilb commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +    const columnLabelContainerStart = -rowLabelContainerStart + 95;
I don't think this columnLabel variable should be tied to the rowLabels at all. This is just `-75 + 95`, you could just make it 20 since it doesn't rely on the rowLabels

2020-09-10 22:16 UTC, JackWilb approved these changes
Looks good to me. Thanks for putting up with the changes to the code format, general fixes, and rebasing!

2020-09-10 23:22 UTC, merged

2020-09-11 13:53 UTC, waxlamp commented
> Looking good. I have several suggestions about how to improve the code, but the visuals are very nice.
> 
> Before merging:
> 
> * [ ]  file an issue to hoist some of the DOM creation to the Vue layer
> * [x]  let's consider rebasing the commit stream to improve the commit messages and/or restructure some of the changes

I see the rebasing was done (nice work); @mozartfish, could you please file the issue I requested and link it here?

Nice job on this PR!